### ISSUE TITLE
Legacy Tedious Prior to v18 Support / Documentation

### ISSUE THREAD

**Issue by mjbergman92** [kysely-org/kysely#1095]
If using Tedious v17 like me for MS SQL*, you must provide the cancel method for the TediousConnection because the type changed from () => void to () => boolean.

*Tedious v18 introduced a driver that does not work for MS SQL Server 2012, or at least the 2012 I need to connect to

**Comment by mjbergman92** [comment]
I understand that according to the Contributing manifest (is it referred to as manifest?, idk), making pull requests is pretty relaxed, which has a lot of upsides as someone who would like to contribute with things that I need for my own.

Could I get some brief direction on contributing to the docs or a link to that? (If it does not exist, I could also do that. I really really like this project).

**Comment by igalklebanov** [comment]
Hey 👋 

Thanks for raising this! This alone will help anyone with the same issue.

Let me see if I understand this correctly..
On `tedious < 18`, you have to pass a `cancel` callback to the connection constructor?
This seems like `tedious` knowledge, and since `kysely` doesn't wrap the connection constructor, it belongs to the `tedious`' documentation.

If there's something on `kysely`'s end that's stopping you, lemme know.

**Comment by mjbergman92** [comment]
I just wanted to point it out. There are several functions, I think like 10 in total that are expected in the new version of tedious. **_CORRECTION_**: Version of tedious > 16 has the additional fields. I tested 17 and have the same issue as 18. I can not do the digging to figure out exactly when the changes came about, but I know that tedious 16.4.1 works for me and after trying to upgrade, it does not, and these 10 or so additional/modified props are required or need modification from the prior instanciation.

**Comment by igalklebanov** [comment]
afaik, `kysely` should still work with `tedious` 16. If you're getting TypeScript errors when creating the dialect instance, just `as any`.
