### ISSUE TITLE
Add a MigratorProps.allowMissingMigrations option

### ISSUE THREAD

**Issue by czeidler** [kysely-org/kysely#1186]
Add an option to allow missing migrations.

Think this would be useful during development. For example, when sharing a db between developers.

Example scenario:
- Developer A is working on feature A and migrates the shared DB to `10_FeatureA` 
- Developer B is working on feature B but can't migrate to `20_FeatureB` because the `10_FeatureA` migration is missing

This behavior is allowed in other migration tools so I think it would be useful to have a config option for it.

I am happy to implement this if there are no objections.

**Comment by koskimas** [comment]
Doesn't the `allowUnorderedMigrations` option already allow you to do this?

**Comment by czeidler** [comment]
This is the code:

https://github.com/kysely-org/kysely/blob/5b79e88d2e932cdffe9d68d83b145f4e86e5d4b3/src/migration/migrator.ts#L468C5-L471C6

I need an `if` check for the `#ensureNoMissingMigrations()` call

**Comment by koskimas** [comment]
No thanks

**Comment by bessey** [comment]
Can I jump in to strong-man an argument for this feature? I agree that sharing a DB between developers is not a great argument for this, but I have experienced another.

I have an application with the following properties:

1. It runs migrations in-process, before web server boot
3. If migrations fail, boot is prevented to ensure app code is not run on a known incompatible schema
4. It has a K8s ready check, so traffic is if boot is prevented, traffic is never sent to the bad app

This all works great, however, in the event of an emergency rollback, Kysely (and Knex's) migration logic causes issues under the following scenario:

1. App v1 is released to production
2. App v2 is released to production, with a backwards compatible migration. It succeeds and traffic shifts to v2
3. A critical runtime error is identified with App v2. To quickly mitigate, App v1 is re-deployed. This avoids the need to merge revert commits and wait for CI, potentially reducing incident response time to seconds.
4. However, v1 now fails to boot because the migrator identifies a missing migration.

The end result: the rollback fails, and you're stuck on a bad version of the app. 

I note that Rails migrator does not error when encountering migrations in the DB not present in source code, presumably in part for this reason.

**Comment by oorestisime** [comment]
@igalklebanov can you folks maybe reconsider this? I dont think its that uncommon to share a DB between dev/local environments. The knex option was handy for that reason. This is still a simple if here https://github.com/kysely-org/kysely/blob/c54987f4d5bb1a9573c8d83e1cba7365770cc016/src/migration/migrator.ts#L586 i can make a PR if you accept :D
