### ISSUE TITLE
Syntax error when invalid query

### ISSUE THREAD

**Issue by hanssonduck** [kysely-org/kysely#340]
If you select from a table without specifying any column will a syntax error will be thrown. Was stuck on this for some time until I released what was wrong. Maybe it's possible to add some descriptive error message when the query leads to invalid sql?

**Comment by koskimas** [comment]
I don't think there's a clean way to have an compile-time error in that case. The only real option is to not have the `execute` methods there at all until a `select` method has been called, but that would just be confusing in a different way. People wouldn't know why the method isn't there.

If there was some way to show an error when there's no `select` call, the error would be there all the time before you do call a `select` method. It would be super annoying since you normally write a large part of the query before calling `select` (joins etc. things that enable selections).

We could throw a better runtime error.
