### ISSUE TITLE
Support for sqlcommenter?

### ISSUE THREAD

**Issue by fritzblue** [kysely-org/kysely#384]
Is support for [sqlcommenter](https://google.github.io/sqlcommenter/) planned? It would be highly useful to be able to automatically attach SQL comments to correlate user code in kysely with executed SQL.

It looks like knex [has support](https://google.github.io/sqlcommenter/node/knex/) fwiw.

**Comment by igalklebanov** [comment]
Hey 👋 

SQLCommenter is a suite of plugins/middlewares, have you tried requesting kysely support on their end?

**Comment by koskimas** [comment]
No answer.

**Comment by smolijar** [comment]
For anyone interested, I've been working on this for the past couple of days and it is now public. Feel free to give it a shot: [kysely-sqlcommenter](https://github.com/smolijar/kysely-sqlcommenter)

```ts
import { SqlCommenterPlugin } from 'kysely-sqlcommenter'

const db = new Kysely<DB>({
  // ... kysely config
  plugins: [
    // Provide callback
    new SqlCommenterPlugin(() => asyncLocalStorage.getStore()),
  ],
})
```

**Comment by thelinuxlich** [comment]
hey, that's nice, I've created this PR specifically for this use case https://github.com/kysely-org/kysely/pull/871

**Comment by smolijar** [comment]
Hey, little update: I migrate to the new API (which is super nice, because it can now operate without monkey patching and easily across all statement types, not just SELECTs). I am running it on production now on GCP to get more of CloudSQL Insights (which is I think why most people come here). 

https://github.com/smolijar/kysely-sqlcommenter

<img width="3748" height="2578" alt="Image" src="https://github.com/user-attachments/assets/48f78cd2-c1b3-4c1e-b771-07783025890e" />
