### ISSUE TITLE
feat: make `$if` a type predicate

### ISSUE THREAD

**Issue by juliusmarminge** [kysely-org/kysely#413]
Currently doesn't look like the `$if(cond, ...)` narrows the type of cond.

Would be nice if it did, so we could skip the non-null-assertions

<img width="961" alt="CleanShot 2023-04-04 at 09 03 32@2x" src="https://user-images.githubusercontent.com/51714798/229714030-5b3f083d-4e1b-41ca-9419-a19e1145e1ae.png">

**Comment by koskimas** [comment]
You shouldn't use `$if` for adding optional `where` expressions. Use normal `if` statements instead like @igalklebanov showed.

**Comment by juliusmarminge** [comment]
> You shouldn't use `$if` for adding optional `where` expressions. Use normal `if` statements instead like @igalklebanov showed.

May I ask when $if should be used then?

**Comment by igalklebanov** [comment]
@juliusmarminge It was created for [conditional selects](https://kysely.dev/docs/recipes/conditional-selects).

**Comment by koskimas** [comment]
I've tried to make that as clear as possible in the documentation but we probably still need to improve that

<img width="941" alt="Screenshot 2023-04-04 at 21 19 29" src="https://user-images.githubusercontent.com/846508/229882824-a1303e5a-803b-4943-9b75-0e12b436bcd5.png">

**Comment by juliusmarminge** [comment]
My bad for not checking the docs properly here. I ended up doing something like this:

<img width="548" alt="CleanShot 2023-04-04 at 21 02 57@2x" src="https://user-images.githubusercontent.com/51714798/229894540-64602e8c-0a56-4950-8dbf-0b7a45f50561.png">


Another (unrelated) quick question when I got you in the thread, what's the "best practice" for breaking out a joined table to it's own object? Is what I'm doing here good/bad?

**Comment by igalklebanov** [comment]
@juliusmarminge Take a look at the [relations recipe](https://kysely.dev/docs/recipes/relations).

**Comment by abellaismail7** [comment]
The current immutable query approach feels a bit inelegant.

I’d like to suggest introducing another method that behaves the same way but doesn’t change the type—this would avoid any impact on performance.

For example, something like:

```js
$on(condition, (val, qb) => {
  return qb.where('column', '=', val);
});
```

This method would be used strictly for filtering data, without affecting the query type.

An even more flexible API could be a generic function like this:

```js
$on(qb => qb);
```

This would allow something like:

```js
$on(mySafeFilter(filter, (val, qb) => qb));
```

I'm not sure whether this is technically feasible, but I wanted to share the idea. If it turns out to be possible, I’d be happy to contribute a PR.

**Comment by igalklebanov** [comment]
@abellaismail7 check out [`$call`](https://kysely-org.github.io/kysely-apidoc/interfaces/SelectQueryBuilder.html#call).
