### ISSUE TITLE
Is it possible to configure Kysely to return `foo | undefined` instead of `foo | null`?

### ISSUE THREAD

**Issue by yannxaver** [kysely-org/kysely#515]
Kysely returns nullable columns as `foo | null`. In my application code I prefer to use `undefined` instead of `null`. Hence I have to convert all `foo | null` fields into `foo | undefined` after retrieving data with Kysely. Is it possible to configure Kysely to return `foo | undefined` instead of `foo | null`?

**Comment by igalklebanov** [comment]
Hey 👋 

This is not possible with Kysely.

There's no such thing as undefined in SQL. 

All built-in dialects use drivers that, by default, transform sql nulls to js nulls.
If you change `foo | null` to `foo | undefined`, you'd have to also align runtime results, otherwise it's not type-safe.

Supporting this requirement will hit compile-time performance and project maintainability (added type complexity) - not worth it for such a niche requirement.
