### ISSUE TITLE
[Feature] SELECT without FROM

### ISSUE THREAD

**Issue by theogravity** [kysely-org/kysely#517]
I'd like support for the following use-case:

```sql
WITH query AS (
    SELECT pgml.embed(model, needle) AS embedding
)
```

I've read from discord that this case isn't supported. Could you create a `.selectBare()` (as a contrast to `.selectFrom()`) to accomplish this?

I have a hack that works, but typescript doesn't like it:

[Playground Link](https://kyse.link/?p=s&i=hrcwDweUyG01KMCYp34j)

**Comment by igalklebanov** [comment]
Hey 👋 

> I've read from Discord that this case isn't supported. Could you create a .selectBare() (as a contrast to .selectFrom()) to accomplish this?

There has to be a good reason to add stuff to Kysely's API, and it has to be type-safe.

Such SQL syntax is both very rare and can not be type-safe, since you'll always have to pass a type.
Adding more `.select` prefixed methods to `QueryCreator` would confuse our consumers.
Can be done easily with sql template tag (just like you did).

> I have a hack that works, but typescript doesn't like it:

Some of what you've done there is erroneous because you removed the existing schema block and didn't define a `DB` interface.
Other issues stem from odd syntax attempts.

Is this what you were going for?
[Playground link](https://kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNC4yoXPaBFZpbXBvcnQgeyBHZW5lcmF0ZWQsIFNlbGVjdGFibGUgfSBmcm9tICJreXNlbHkiCgpkZWNsYXJlIGdsb2JhbCB7CiAgaW50ZXJmYWNlIERCIHsKICAgIGRvY3VtZW50X2NodW5rX2VtYmVkZGluZzogRG9jdW1lbnRDaHVua0VtYmVkZGluZ1RhYmxlCiAgICBkb2N1bWVudF9jaHVuazogRG9jdW1lbnRDaHVua1RhYmxlCiAgfQp9CgpleHBvcnQgaW50ZXJmYWNlIERvY3VtZW50TWV0YWRhdGEgewogIGFwcElkPzogc3RyaW5nCiAgcmVzb3VyY2VJZD86IHN0cmluZwogIGNsaWVudElkPzogc3RyaW5nCn0KCmV4cG9ydCBpbnRlcmZhY2UgRG9jdW1lbnRUYWJsZSB7CiAgLyoqCiAgICogVGhpcyBpcyBhIHVzZXIgKGRldikgZ2VuZXJhdGVkIHZhbHVlIHVzaW5nCiAgICogZ2VuZXJhdGVFbWJlZERvY3VtZW50SWQoKS4gVGhpcyBpcyBzbyB3ZSBjYW4KICAgKiBlYXNpbHkgbG9vayB1cCB0aGUgcmVsYXRlZCBkb2N1bWVudCBmcm9tIGl0cyBvcmlnaW5hbAogICAqIHNvdXJjZSBmb3IgdGhlIHB1cnBvc2VzIG9mIGRlbGV0aW9uIC8gdXBkYXRlLgogICAqLwogIGlkOiBzdHJpbmcKICB3b3Jrc3BhY2VfaWQ6IHN0cmluZwogIHJvb21faWQ6IHN0cmluZwogIHRleHRfY29udGVudDogc3RyaW5nCiAgbW9kZWw6IHN0cmluZwogIGNyZWF0ZWRfYXQ6IEdlbmVyYXRlZDxEYXRlPgogIGNvbnRlbnRfdHlwZTogc3RyaW5nCiAgbWV0YWRhdGE_OiBEb2N1bWVudE1ldGFkYXRhCiAgdmVyc2lvbjogbnVtYmVyCn0KCmV4cG9ydCBpbnRlcmZhY2UgRG9jdW1lbnRDaHVua1RhYmxlIHsKICBpZDogR2VuZXJhdGVkPG51bWJlcj4KICBkb2N1bWVudF9pZDogc3RyaW5nCiAgY3JlYXRlZF9hdDogR2VuZXJhdGVkPERhdGU-CiAgdGV4dDogc3RyaW5nCn0KCmV4cG9ydCBpbnRlcmZhY2UgRG9jdW1lbnRDaHVua0VtYmVkZGluZ1RhYmxlIHsKICBkb2N1bWVudF9jaHVua19pZDogbnVtYmVyCiAgY3JlYXRlZF9hdDogR2VuZXJhdGVkPERhdGU-CiAgZW1iZWRkaW5nOiBudW1iZXJbXQp9CgpleHBvcnQgdHlwZSBEb2N1bWVudFJvdyA9IFNlbGVjdGFibGU8RG9jdW1lbnRUYWJsZT4KZXhwb3J0IHR5cGUgRG9jdW1lbnRDaHVua1JvdyA9IFNlbGVjdGFibGU8RG9jdW1lbnRDaHVua1RhYmxlPgqhcdoCzGltcG9ydCB7IHNxbCB9IGZyb20gImt5c2VseSIKCmNvbnN0IHJvd3MgPSBhd2FpdCBreXNlbHkKICAud2l0aCgKICAgICJxdWVyeSIsCiAgICAoKSA9PgogICAgICBzcWw8eyBlbWJlZGRpbmc6IGFueSB9PmAoU0VMRUNUIHBnbWwuZW1iZWQoJHtzcWwudmFsKCJtb2RlbCIpfSwgJHtzcWwudmFsKAogICAgICAgICJ0ZXh0IiwKICAgICAgKX0pIGFzIGVtYmVkZGluZylgLAogICkKICAuc2VsZWN0RnJvbShbImRvY3VtZW50X2NodW5rX2VtYmVkZGluZyIsICJxdWVyeSJdKQogIC5pbm5lckpvaW4oCiAgICAiZG9jdW1lbnRfY2h1bmsiLAogICAgImRvY3VtZW50X2NodW5rX2VtYmVkZGluZy5kb2N1bWVudF9jaHVua19pZCIsCiAgICAiZG9jdW1lbnRfY2h1bmsuaWQiLAogICkKICAuc2VsZWN0KChlYikgPT4gWwogICAgImRvY3VtZW50X2NodW5rX2VtYmVkZGluZy5kb2N1bWVudF9jaHVua19pZCIsCiAgICAiZG9jdW1lbnRfY2h1bmsudGV4dCBhcyBzaW1pbGFyaXR5IiwKICAgIGViCiAgICAgIC5mbigicGdtbC5jb3NpbmVfc2ltaWxhcml0eSIsIFsKICAgICAgICAiZG9jdW1lbnRfY2h1bmtfZW1iZWRkaW5nLmVtYmVkZGluZyIsCiAgICAgICAgInF1ZXJ5LmVtYmVkZGluZyIsCiAgICAgIF0pCiAgICAgIC5hcygiY29zaW5lX3NpbWlsYXJpdHkiKSwKICBdKQogIC5vcmRlckJ5KCJzaW1pbGFyaXR5IiwgImRlc2MiKQogIC5saW1pdCg1KQogIC5leGVjdXRlKCkKoWPD)

**Comment by theogravity** [comment]
> Hey 👋
> 
> > I've read from Discord that this case isn't supported. Could you create a .selectBare() (as a contrast to .selectFrom()) to accomplish this?
> 
> There has to be a good reason to add stuff to Kysely's API, and it has to be type-safe.
> 
> Such SQL syntax is both very rare and can not be type-safe, since you'll always have to pass a type. Adding more `.select` prefixed methods to `QueryCreator` would confuse our consumers. Can be done easily with sql template tag (just like you did) - we perhaps need to make its usage in `with` clause smoother.
> 
> > I have a hack that works, but typescript doesn't like it:
> 
> Some of what you've done there is erroneous because you removed the existing global schema block and didn't define a `DB` interface. Not passing a type to sql template tag in the `with` clause. Other issues stem from odd syntax attempts.
> 
> Is this what you were going for?

It's better, but the query part actually needs to be at the end of the innerJoin.

Here's the working version with your additions and my fixes to it (but still with typescript issues):

[Playground Link](https://kyse.link/?p=b&i=haFkqHBvc3RncmVzoXamMC4yNC4yoXPaBFZpbXBvcnQgeyBHZW5lcmF0ZWQsIFNlbGVjdGFibGUgfSBmcm9tICJreXNlbHkiCgpkZWNsYXJlIGdsb2JhbCB7CiAgaW50ZXJmYWNlIERCIHsKICAgIGRvY3VtZW50X2NodW5rX2VtYmVkZGluZzogRG9jdW1lbnRDaHVua0VtYmVkZGluZ1RhYmxlCiAgICBkb2N1bWVudF9jaHVuazogRG9jdW1lbnRDaHVua1RhYmxlCiAgfQp9CgpleHBvcnQgaW50ZXJmYWNlIERvY3VtZW50TWV0YWRhdGEgewogIGFwcElkPzogc3RyaW5nCiAgcmVzb3VyY2VJZD86IHN0cmluZwogIGNsaWVudElkPzogc3RyaW5nCn0KCmV4cG9ydCBpbnRlcmZhY2UgRG9jdW1lbnRUYWJsZSB7CiAgLyoqCiAgICogVGhpcyBpcyBhIHVzZXIgKGRldikgZ2VuZXJhdGVkIHZhbHVlIHVzaW5nCiAgICogZ2VuZXJhdGVFbWJlZERvY3VtZW50SWQoKS4gVGhpcyBpcyBzbyB3ZSBjYW4KICAgKiBlYXNpbHkgbG9vayB1cCB0aGUgcmVsYXRlZCBkb2N1bWVudCBmcm9tIGl0cyBvcmlnaW5hbAogICAqIHNvdXJjZSBmb3IgdGhlIHB1cnBvc2VzIG9mIGRlbGV0aW9uIC8gdXBkYXRlLgogICAqLwogIGlkOiBzdHJpbmcKICB3b3Jrc3BhY2VfaWQ6IHN0cmluZwogIHJvb21faWQ6IHN0cmluZwogIHRleHRfY29udGVudDogc3RyaW5nCiAgbW9kZWw6IHN0cmluZwogIGNyZWF0ZWRfYXQ6IEdlbmVyYXRlZDxEYXRlPgogIGNvbnRlbnRfdHlwZTogc3RyaW5nCiAgbWV0YWRhdGE_OiBEb2N1bWVudE1ldGFkYXRhCiAgdmVyc2lvbjogbnVtYmVyCn0KCmV4cG9ydCBpbnRlcmZhY2UgRG9jdW1lbnRDaHVua1RhYmxlIHsKICBpZDogR2VuZXJhdGVkPG51bWJlcj4KICBkb2N1bWVudF9pZDogc3RyaW5nCiAgY3JlYXRlZF9hdDogR2VuZXJhdGVkPERhdGU-CiAgdGV4dDogc3RyaW5nCn0KCmV4cG9ydCBpbnRlcmZhY2UgRG9jdW1lbnRDaHVua0VtYmVkZGluZ1RhYmxlIHsKICBkb2N1bWVudF9jaHVua19pZDogbnVtYmVyCiAgY3JlYXRlZF9hdDogR2VuZXJhdGVkPERhdGU-CiAgZW1iZWRkaW5nOiBudW1iZXJbXQp9CgpleHBvcnQgdHlwZSBEb2N1bWVudFJvdyA9IFNlbGVjdGFibGU8RG9jdW1lbnRUYWJsZT4KZXhwb3J0IHR5cGUgRG9jdW1lbnRDaHVua1JvdyA9IFNlbGVjdGFibGU8RG9jdW1lbnRDaHVua1RhYmxlPgqhcdoDimltcG9ydCB7IHNxbCB9IGZyb20gImt5c2VseSIKCmNvbnN0IHJvd3MgPSBhd2FpdCBreXNlbHkKICAud2l0aCgKICAgICAgICAncXVlcnknLAogICAgICAgICgpID0-IHNxbDx7IGVtYmVkZGluZzogYW55IH0-YChTRUxFQ1QgcGdtbC5lbWJlZCgke3NxbC52YWwoJ21vZGVsJyl9LCAke3NxbC52YWwoJ3RleHQnKX0pIGFzIGVtYmVkZGluZylgLAogICAgICApCiAgICAgIC5zZWxlY3RGcm9tKCdkb2N1bWVudF9jaHVua19lbWJlZGRpbmcnKQogICAgICAvLyBlc2xpbnQtZGlzYWJsZS1uZXh0LWxpbmUgQHR5cGVzY3JpcHQtZXNsaW50L2Jhbi10cy1jb21tZW50CiAgICAgIC8vQHRzLWlnbm9yZQogICAgICAuaW5uZXJKb2luKCdkb2N1bWVudF9jaHVuaycsICdkb2N1bWVudF9jaHVua19lbWJlZGRpbmcuZG9jdW1lbnRfY2h1bmtfaWQnLCBzcWwucmF3KCdkb2N1bWVudF9jaHVuay5pZCwgcXVlcnknKSkKICAgICAgLnNlbGVjdCgoZWIpID0-IFsKICAgICAgICAnZG9jdW1lbnRfY2h1bmtfZW1iZWRkaW5nLmRvY3VtZW50X2NodW5rX2lkJywKICAgICAgICAnZG9jdW1lbnRfY2h1bmsudGV4dCBhcyBzaW1pbGFyaXR5JywKICAgICAgICBlYgogICAgICAgICAgLy8gZXNsaW50LWRpc2FibGUtbmV4dC1saW5lIEB0eXBlc2NyaXB0LWVzbGludC9iYW4tdHMtY29tbWVudAogICAgICAgICAgLy9AdHMtaWdub3JlCiAgICAgICAgICAuZm48bnVtYmVyPigncGdtbC5jb3NpbmVfc2ltaWxhcml0eScsIFsnZG9jdW1lbnRfY2h1bmtfZW1iZWRkaW5nLmVtYmVkZGluZycsICdxdWVyeS5lbWJlZGRpbmcnXSkKICAgICAgICAgIC5hcygnY29zaW5lX3NpbWlsYXJpdHknKSwKICAgICAgXSkKICAgICAgLm9yZGVyQnkoJ3NpbWlsYXJpdHknLCAnZGVzYycpCiAgICAgIC5saW1pdCg1KQogICAgICAuZXhlY3V0ZSgpCqFjww==)

**Comment by igalklebanov** [comment]
> the query part actually needs to be at the end of the innerJoin

I see, really curious about this.

> Here's the working version with your additions and my fixes to it (but still with typescript issues)

Thank you!

**Comment by theogravity** [comment]
Very close

<img width="1386" alt="image" src="https://github.com/kysely-org/kysely/assets/855434/570e5429-067c-4c73-a60f-7737e3777694">

**Comment by koskimas** [comment]
This is merged and will be released in the version 0.27.0 (the next version).

After a lot of thought we ended up with the weird function name `selectNoFrom`. The obvious name choice would be just `select` BUT new users would instinctively call that instead of `selectFrom` since that's how a select statement begins. `selectNoFrom` should make it clear that `selectFrom` is the correct option.

**Comment by koskimas** [comment]
@igalklebanov I forgot @theogravity's suggestion `selectBare`. I think it sounds better. Should we switch to that?

**Comment by igalklebanov** [comment]
it's OK, it might be confusing to non-native speakers. where `noFrom` and `from` give a very good hint. But I'm OK with both.

**Comment by koskimas** [comment]
Ok, let's keep selectNoFrom.

**Comment by OultimoCoder** [comment]
Looking forward to this release will solve some headache I have been having!

**Comment by brett-minca** [comment]
Same, I'm really excited for this feature.  Thanks, @koskimas!
