### ISSUE TITLE
Bug: SKIP LOCKED can't come before FOR UPDATE

### ISSUE THREAD

**Issue by Schniz** [kysely-org/kysely#614]
([playground link here](https://kyse.link/?p=s&i=vzSHwpZMEOv8eyMz1fXj))
The following code:

```ts
const rows = await kysely
  .selectFrom("user")
  .select(["id", "last_name"])
  .skipLocked()
  .forUpdate()
  .execute()
```

is translated into

```sql
SELECT
  "id",
  "last_name"
FROM
  "user" SKIP LOCKED
FOR UPDATE
```

which is a malformed SQL. The correct statement will put `SKIP LOCKED` after `FOR UPDATE`:
```sql
SELECT
  "id",
  "last_name"
FROM
  "user" SKIP LOCKED
FOR UPDATE
```

moreover, AFAIK `SKIP LOCKED` must come with `FOR UPDATE` or `FOR SHARE`, and the API does not limit it right now. But for now, it would be best if the query builder could put the `.skipLocked()` anywhere in the builder chain

**Comment by koskimas** [comment]
Move the method call after forUpdate.

**Comment by Schniz** [comment]
That's what I was doing... still seems like a bug given that all other statements can be used anywhere in the builder

**Comment by koskimas** [comment]
We could always put `SKIP LOCKED` after `FOR UPDATE` or `FOR SHARE`. That's something that makes sense. But not having `skipLocked()` method available unless `forUpdate` or `forShare` is not called, is not feasible. It would mean either

1. Adding another type argument for `SelectQueryBuilder` just for this tiny improvement. The argument would travel EVERYWHERE in the codebase.
2. Having multiple versions of `SelectQueryBuilder` that branch from the `forUpdate` and `forShare` calls. Because of the complex types, we can't really use inheritance. We'd need to copy paste the whole `SelectQueryBuilder` multiple times with minor alterations. That's also not going to happen for a tiny improvement.

Not everything is a bug. This is just an imperfection in the API. The API is not perfect. We need to make compromises to keep the codebase maintainable.

**Comment by Schniz** [comment]
Totally agree. I understand that this can be hard to maintain. But if we can make SKIP LOCKED be always after FOR UPDATE that can be cool. I wanted to tackle this task when I have some free time in my parental leave if it makes sense to you. I won’t do that if you think it’s redundant though 🙏

**Comment by koskimas** [comment]
I can quickly fix this now. Thanks for the offer though 👍
