### ISSUE TITLE
Q: Mapping of table and column names

### ISSUE THREAD

**Issue by hinogi** [kysely-org/kysely#619]
Since there is an interface for the database schema, is it possible to change the reference name to tables and columns?
you know if you have a table like `U_pro_isbn` or something and you don't want to carry that over into the usage in the code :D

**Comment by igalklebanov** [comment]
Hey 👋 

First of all, I don't like this. You can simply alias tables and columns in the queries themselves and not hide this or introduce complexity/surprise elements to your codebase. Also, instead of manually defining types, we encourage using a types codegen library in production (kysely-codegen, prisma-kysely or kanel-kysely) and this just denies it.

You can implement a custom plugin that uses a node transformer to override identifiers, see [example](https://github.com/kysely-org/kysely/tree/master/src/plugin/camel-case). It should receive a fake-to-real mapping object in its constructor. You'd then apply it globally in Kysely's configuration.

Alternatively, you can extend the dialect you're using and override the identifier method in the compiler class.

**Comment by hinogi** [comment]
From a DDD perspective, often the table names are not preferable because they do not provide immediate information only if you already know what they represent. So for interfacing the database you have to have database knowledge instead of domain knowledge, that's the reason for that question.
And since it is already possible to use an abstract schema of the database as typescript types/interfaces I thought it would be cool to have that.
Beside Oracle to currently not being availabe, would the codegen would get all tables and columns? Because that would be some unnecessary overhead for my purpose.

**Comment by koskimas** [comment]
A custom plugin is what you should use.
