### ISSUE TITLE
Optionally disable transaction on migrations

### ISSUE THREAD

**Issue by volnei** [kysely-org/kysely#644]
Using kysely through vercel/storage that currently does not supports transactions. 
I think would be simple to disable transactions on migration, is that possible?

**Comment by igalklebanov** [comment]
Hey 👋 

It should have been disabled in the dialect implementation, by returning `false` in the adapter's `supportsTransactionalDdl` method.
Looking at https://github.com/vercel/storage/blob/main/packages/postgres-kysely/src/index.ts, they've only handled the driver part, but the adapter is unchanged - https://github.com/kysely-org/kysely/blob/db8999b64af504eafd8a84ce9f28954bb5a7e15a/src/dialect/postgres/postgres-adapter.ts, which is why it tries to perform migrations with transactions.
