### ISSUE TITLE
Allow for empty selects with CTEs

### ISSUE THREAD

**Issue by icopp** [kysely-org/kysely#651]
When working with Postgres and CTEs, it's pretty normal to have a query like...

```sql
WITH cte_1 as (
  ...
),
WITH cte_2 as (
  ...
),
WITH cte_3 as (
  ...
)
SELECT true;
```

...as a way to have a multi-table and effectively transactional update without actually needing a transaction on the client side.

However, the current structure of Kysely requires that all queries have a specific table that they're selecting from, without being able to have an effectively empty select statement like that.

While obviously it's simple to work around that by moving the last CTE into the main body, it would be more elegant if the API allowed something like a `selectEmpty()` for these use cases.

**Comment by koskimas** [comment]
The next version allow you to create select statements without a FROM clause. We've already implemented it. Stay tuned.

**Comment by koskimas** [comment]
0.26.2 is now released. No release notes yet unfortunately. Didn't have time to write them.

There's a `selectNoFrom` function that can be used to create select expressions without a from clause. The name is weird, I know, I'll explain it in the release notes. Short version: `select` would've caused people to use it instead of `selectFrom`.
