### ISSUE TITLE
How to edit compiled query?

### ISSUE THREAD

**Issue by dinfer** [kysely-org/kysely#666]
I'm creating queries in browser and execute them on server.
I want to edit the compiled query on server side because sensitive information should not be queried like password or tokens.

**Comment by koskimas** [comment]
You could send the query "node" instead of the compiled query and compile it in the backend. But I very much advice against doing something like this. You're exposing backend to countless injection attack possibilities if you allow the frontend to build the query.

If you really want to do this, see the `toOperationNode` method instead of `compile`. You can the compile it using the `DefaultQueryCompiler` subclasses (there's one for each dialect).
