### ISSUE TITLE
Question: Reusable select query helpers

### ISSUE THREAD

**Issue by emiliedebra** [kysely-org/kysely#670]
Hi all, thanks for such a great library!

I am currently using Kysely `v0.26.1` with the Postgres Dialect.

On this version I am able to create handy little reusable `selections` which I can pass into the `select()` function call.
This looks like the following:

```ts
const personPetSelect = (eb: ExpressionBuilder<DB & { petJoin: Pet }, 'person' | 'petJoin'>) => 
  [
     'person.id',
     'petJoin.name'
  ] as const;
```

Which could be used like so, with an inner or left join:

```ts
const leftJoinResult = await db
   .selectFrom('person')
   .leftJoin('pet as petJoin', 'pet.owner_id', 'person.id')
   .select(personPetSelect)
   .execute();
  
const innerJoinResult = await db
   .selectFrom('person')
   .innerJoin('pet as petJoin', 'pet.owner_id', 'person.id')
   .select(personPetSelect)
   .execute();
```

This was all type-happy and would generate the correct nullable result fields based on the type of join.
I could also use the reusable select helper in a query that has more joins than what I defined in the ExpressionBuilder type within the reusable select helper, so long as what was defined there was still available within the query.

Ie, I could still use it in a query that looked like this:

```ts
const twoJoinsResult = await db
   .selectFrom('person')
   .leftJoin('pet as petJoin', 'pet.owner_id', 'person.id')
   .leftJoin('house', 'house.owner_id', 'person.id')
   .select((eb) => [
        ...personPetSelect(eb),
        'house.address'
    ])
   .execute();
```

However, upon upgrading to v0.26.3, there seem to be some type changes which are causing these helpers to no longer work.
1. Depending on the join, the table types change to include a `Nullable` wrapper which I would need to define within my ExpressionBuilder type definition. `Nullable` is not exposed to me from the library.
2. It seems that type of `eb` has to _exactly_ match, meaning that I cannot define a select helper to use a subset of tables and then use that as I described above between the first and second blocks of queries. This is likely because the `leftJoin` on `house` would have nullified the `House` table, whereas my function technically expects it to be non-null, even though I am not specifying that I can select from it.

I was wondering, is this type of helper something I can still expect to be able to do? Is there something I can do within my function declaration to better define the types and what I am trying to achieve?

Thanks so much!

**Comment by koskimas** [comment]
The types in 0.26.3 are even more strict, which causes this change.

The `Nullable` helper is super simple. You can just copy-paste it to your codebase.

https://kyse.link/?p=s&i=83ZyHHBSEtF5Eajcds16

Optionally you can simply define the helper using the narrowest type needed:

https://kyse.link/?p=s&i=owLOtHk7aaiozfPTySKb

You probably have something that uses the `eb` in you real code, since this particular example could be written simply like this:

https://kyse.link/?p=s&i=AyoQtR4b2UPQm3PIZYjD

**Comment by SahidMiller** [comment]
Hello! I just ran into this today after upgrading and adding a leftJoin. For me, the solution was to move the unrelated join **after** the unrelated select(s) and follow the join up with it's own select statements.

**Comment by WoodyWoodsta** [comment]
@koskimas The examples you gave are contrived in that the select covers all possible cases (conversely the DB schema is the same width as the select example). With a small extension to your example, I now have a select which doesn't work with the DB schema due to an intermediate left join that the select helper is not concerned about: https://kyse.link/?p=s&i=1ZWFUIGCHSJCCGb41A3j

How do we solve the types for this case, bearing in mind DB schemas can get many times more complex?

**Comment by koskimas** [comment]
@WoodyWoodsta You can't get generic __and__ strictly typed solution that works in all cases. If you want generic, you need to let go of strict types. Even typescript has its limits. You need to build these things case by case.

**Comment by koskimas** [comment]
Here's a generic, but slightly less type-safe version https://kyse.link/?p=s&i=1ZWFUIGCHSJCCGb41A3j

The function argument is used to check that the required `petJoin` join is there, but we can't use that builder directly because of the very generic type. Instead we create another typed expression builder.

You'll need to keep those two builders in sync, but that's pretty much the best that we can do here.

**Comment by koskimas** [comment]
I just got an idea that might help a lot in these kind of cases. Let's see if it turns out to be a brainfart or a good idea. https://github.com/kysely-org/kysely/issues/696

**Comment by koskimas** [comment]
@WoodyWoodsta @emiliedebra I was kinda lost with this before. I finally figured out what the issue was in my examples. When you `leftJoin` a table that has a column that some other table also has, that column becomes nullable too because it gets overridden by the similarly named column. So the issue all along was an incorrectly defined subtype in the selection helper. See this example https://kyse.link/?p=s&i=Kew6rc2niwbgyh7WPQ9F.

In the new example I've only declared the exact subset of tables and columns I need in the helper. That way there's a minimum amount of stuff to get right. If you don't use a table in a helper, don't add it to the expression builder type. If you don't use a column of a table, the same thing.

The weird and thing in this example is this part `parent: { id: string | null }`. `id` shouldn't be nullable right? Actually selecting just `id` without a table specifier would be nullable because you left-joined `parent` that also has an `id`.

So it's possible to create helpers like this, but figuring out the types can be difficult. A good approach is to only declare columns and tables you use. Then if the it still doesn't work, try to figure out which columns can be null based on the left joins.

Nullable columns work with all join types since `T extends T | null`.

**Comment by WoodyWoodsta** [comment]
Thanks @koskimas - appreciate your looking into this. Will try what you have suggested - the example appears to achieve what we require.

**Comment by emiliedebra** [comment]
Thanks @koskimas - have tried what you suggested in your last post and it seems to do the trick. I appreciate all the time spent on this!

**Comment by emiliedebra** [comment]
Hi again, I was playing around with this a bit more and I found some interesting behaviour regarding left vs inner joins and the use of `jsonBuildObject` within a select helper.

When I do either type of join, if I select a column directly it will correctly make the return type nullable or not. Ie, if I select `petJoin.name` when I have done a left join I get `string | null` and with an inner join I get `string`.

However, that exact same selection placed inside a `jsonBuildObject` call always returns a 'nullable' type regardless of the join.

See here, building on your previous example: https://kyse.link/?p=s&i=W7uGY0ft8MuWMuMCrsBQ
 
 Is this expected or does this seem like incorrect behaviour?

**Comment by flodlc** [comment]
Hi @koskimas, after reading this discussion I feel that there is a drawback with this new way to manage columns with same names.
Here is how I use kysely with v0.26.3:
In this exemple, is there a good way to have a `string` typed `userId` in the result ?
https://kyse.link/?p=s&i=fffAeKnaVNJglZmSBEN9

In version 0.26.0  was able to have a `string` typed `userId` giving the full DB type definition in the helper:
https://kyse.link/?p=s&i=gsApcGBMfjoEDw8PmoQs 

Thanks for your help !

**Comment by RobinClowers** [comment]
I agree, I'm also running into this limitation. Using `Pick<Pet, 'owner_id'>` works if the query only has a single `owner_id` column, but if another relation also has the same column name, I get type errors. 

@flodlc Those links seem to have the exact same content when I open them?

**Comment by flodlc** [comment]
I edited the links, thanks !

**Comment by emiliedebra** [comment]
@koskimas any chance you could take a look?

**Comment by RobinClowers** [comment]
I was able to work around this for my case, by using a subquery instead of a an expression builder. This might not work in all cases (I suspect it will perform much worse in some cases, though it didn't in mine), but it worked in my example:

```typescript
export function getOwners() {
  return queryBuilder.selectFrom("mz_catalog.mz_roles as r").select((eb) => [
    "r.id",
    eb
      .or([
        eb.fn("mz_is_superuser", []),
        eb.fn("has_role", [sql.id("current_user"), "r.oid", sql.lit("USAGE")]),
      ])
      .$castTo<boolean>()
      .as("isOwner"),
  ]);
}

// in my query
queryBuilder
  .selectFrom("mz_catalog.mz_connections as c")
   .innerJoin(getOwners().as("owners"), "owners.id", "c.owner_id")
  .select(["c.name", "owners.isOwner"])
```

**Comment by flodlc** [comment]
@RobinClowers  It seems that last releases have solved the issue ! 
Thanks a lot @koskimas
