### ISSUE TITLE
Extending SelectQueryBuilder now that its an interface

### ISSUE THREAD

**Issue by clintwood** [kysely-org/kysely#716]
`SelectQueryBuilder` and `RawBuilder` were converted to interfaces in PR #589 

The implementation classes (`SelectQueryBuilderImpl`, `RawBuilderImpl`) are not exported which prevents extending the class via module augmentation as suggested here in [Extending using module augmentation](https://kysely.dev/docs/recipes/extending-kysely#extending-using-module-augmentation).

What is the proposed method for extending these if the implementation implementation classes are not exported?

**Comment by koskimas** [comment]
Augmentation was never a proposed way of doing things.
<img width="537" alt="Screenshot 2023-09-27 at 7 11 29" src="https://github.com/kysely-org/kysely/assets/846508/58096cc7-7cf3-471f-a727-25652098ea48">

There's currently no way to get that done. We actually are probably going to go back to exposing classes instead of interfaces because they seem to cause serious typescript performance issues.

**Comment by cubxx** [comment]
there is a hack but type-unsafe way:

```ts
import { createSelectQueryBuilder } from 'kysely'

declare module 'kysely' {
  interface SelectQueryBuilder<DB, TB, O> {
    myLimit(): SelectQueryBuilder<DB, TB, O>;
  }
}
createSelectQueryBuilder().constructor.prototype.myLimit = function () {
  return createSelectQueryBuilder({
      ...this.#props,
      queryNode: SelectQueryNode.cloneWithLimit(
        this.#props.queryNode,
        LimitNode.create(parseValueExpression(100)),
      ),
    })
}
```
