### ISSUE TITLE
Ignore extra attributes

### ISSUE THREAD

**Issue by ozum** [kysely-org/kysely#820]
I couldn't find a way to ignore extra attributes in insert/update operations. 

```sql
CREATE TABLE Example (
  a number;
  b number;
)
```

```ts
const data = { a: 1, b: 2, c: 3 };
await db.insertInto("Example").values(data).execute; // SqliteError: table Example has no column named c
```

I know this is a big and heavy request since type definitions are unavailable at runtime, and there currently is no way for Kysely to know what fields are available in the database engine.

I would appreciate if you can consider this as a long-term feature request.

Kind regards,

**Comment by igalklebanov** [comment]
Hey 👋

Data transformation and runtime schema is out of scope for Kysely's core.

Compile-time errors when objects exceed interface is a flaw in TypeScript, has an open issue for years now. I know a hack that solves this, but we haven't introduced it because it's risky and hurts compilation time.

If you're using PostgreSQL, I believe kanel-zod and kanel-kysely can be combined to have types, validation and automatic omit of unexpected properties. You could also define your own Zod schemas and use them as source of truth for types you pass to Kysely.

You could implement a plugin that recieves a Zod schema, and on insert/update queries, validates the data and omits.

**Comment by ozum** [comment]
Thanks for the fast response.
