### ISSUE TITLE
Support ADD COLUMN IF NOT EXISTS and DROP COLUMN IF EXISTS

### ISSUE THREAD

**Issue by futpib** [kysely-org/kysely#889]
Postgres supports this https://www.postgresql.org/docs/current/sql-altertable.html

**Comment by sagarrajak** [comment]
I think this pr [pr](https://github.com/kysely-org/kysely/pull/900) already closed this issue

**Comment by tansin** [comment]
It would be very nice if DROP COLUMN IF EXISTS would be supported (at least on postgres). At the moment it is the only expression which we have to write in raw SQL in our down migrations. We want to have "IF EXISTS" in down migrations because during development we have to migrate down very often. Sometimes the columns are not there due to a half implemented state of the code or simply development bugs. We expect the down migrations to be idempotent and forgiving in our case. We do not expect down migrations to be applied in production, because of many cases where down migrations are destructive. Is it possible to reopen the issue to complete its second part? Thanks in advance! @koskimas @igalklebanov
